# Generated by Django 6.0.6 on 2026-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_merge_20260728_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
